language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
  allow_failures:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
# command to install dependencies
install:
# add new stuff to requirements file, not here
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest --cov=gastop/

after_script:
  - coveralls

notifications:
    slack:
      rooms:
        - princetonmae:MyikIXs3nE7eGCiIODO5VDxK
      on_failure: always
      on_success: change
