language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install numpy
  - pip install matplotlib
  - pip install configobj
# command to run tests
script:
  - pytest
notifications:
    slack:
      rooms:
        - princetonmae:MyikIXs3nE7eGCiIODO5VDxK
      on_failure: always
      on_success: change
