language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install numpy
  - pip install matplotlib
# command to run tests
script:
  - pytest
notifications:
    slack: princetonmae:MyikIXs3nE7eGCiIODO5VDxK
